version: '3.4'

services:
   librarydb:
    container_name: librarydb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
       - "27017:27017"
    
   libraryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "LibraryDBSettings:ConnectionString=mongodb://librarydb:27017/"
    depends_on:
      - librarydb
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8000:80"
